/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class runtime_Runtime */

#ifndef _Included_runtime_Runtime
#define _Included_runtime_Runtime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     runtime_Runtime
 * Method:    mov0
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_runtime_Runtime_mov0
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     runtime_Runtime
 * Method:    lea0
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_runtime_Runtime_lea0
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
