/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javaapplication1_HelloWorld */

#ifndef _Included_javaapplication1_HelloWorld
#define _Included_javaapplication1_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javaapplication1_HelloWorld
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javaapplication1_HelloWorld_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
