/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_syr_bytecast_runtime_Runtime */

#ifndef _Included_edu_syr_bytecast_runtime_Runtime
#define _Included_edu_syr_bytecast_runtime_Runtime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_syr_bytecast_runtime_Runtime
 * Method:    printString
 * Signature: ([C[CI)V
 */
JNIEXPORT void JNICALL Java_edu_syr_bytecast_runtime_Runtime_printString
  (JNIEnv *, jobject, jcharArray, jcharArray, jint);

#ifdef __cplusplus
}
#endif
#endif
